name: animated_glitch
description:  Animated Glitch is a Flutter package that allows you to easily create glitch effects and control them
version: 3.0.0
homepage: https://github.com/feduke-nukem/animated_glitch
repository: https://github.com/feduke-nukem/animated_glitch
issue_tracker: https://github.com/feduke-nukem/animated_glitch/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
